//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 公告文本校对程序 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class LoadSettingContent : global::System.Configuration.ApplicationSettingsBase {
        
        private static LoadSettingContent defaultInstance = ((LoadSettingContent)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LoadSettingContent())));
        
        public static LoadSettingContent Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 图片路径 {
            get {
                return ((string)(this["图片路径"]));
            }
            set {
                this["图片路径"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 文本路径 {
            get {
                return ((string)(this["文本路径"]));
            }
            set {
                this["文本路径"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 记录页码 {
            get {
                return ((string)(this["记录页码"]));
            }
            set {
                this["记录页码"] = value;
            }
        }
    }
}
